name       : ruby-msgpack
version    : 1.1.0
release    : 3
source     :
    - https://rubygems.org/downloads/msgpack-1.1.0.gem : 07d27ad7563ec84adf6881e2aee2942c45f8d62938401bd15a922cd34ee06732
license    : Apache-2.0
component  : programming.library
summary    : A binary-based efficient object serialization library.
description: |
    MessagePack is a binary-based efficient object serialization library. It enables to exchange
    structured objects between many languages like JSON. But unlike JSON, it is very fast and
    small.
extract    : no
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/msgpack-$version.gem
