name       : ruby-msgpack
version    : 1.2.2
release    : 4
source     :
    - https://rubygems.org/downloads/msgpack-1.2.2.gem : 2136d3836ec8c4a10630d20fc4238fc06ebc913a766eedc618d9cab49bd320aa
license    : Apache-2.0
component  : programming.ruby
extract    : no
summary    : RubyGem - msgpack
description: |
    MessagePack is a binary-based efficient object serialization library. It enables to exchange
    structured objects between many languages like JSON. But unlike JSON, it is very fast and
    small.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    %gem_install
